#XRAY for JIRA integration
EMAIL_JENKINS_NOTIFICATION= fsboui@cegid.com
# sample value: 7aab60d5-1342-6fy5-3xh3-k98c6g06j012  
SERVER_INSTANCE= 318e857e-9f55-40b8-ac58-6899350c32cd
PROJECT_KEY= ATCTT3xFfGN0Mr67foP00fyXqOABg4i34nO8-1iIf0JLORsIKo_ukn8POQlB12aO5eONoyuPRDHHrnAlKSJqZO_-8-NV67--EDwwtIbYjlMBXmn2fQYERV2Af54hO-j-H2fCSXfswK1PCcLULULNksqoIbbbUPU6mlTSUXUDm9KAlTYRSgu7awQ=62398683
TEST_PLAN_KEY = XSP-58
